### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;

### ISSUE THREAD

**Issue by suo801** [fengzhizi715/SAF-AOP#8]
gradle:3.2.0
使用 @Safe时报错：
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
        at com.safframework.log.L.<clinit>(L.kt:52)
        at com.safframework.aop.SafeAspect.safeMethod(SafeAspect.java:34)
        at com.safframework.aop.SafeAspect.ajc$inlineAccessMethod$com_safframework_aop_SafeAspect$com_safframework_aop_SafeAspect$safeMethod(SafeAspect.java:1)
        at com.safframework.aop.SafeAspect.doSafeMethod(SafeAspect.java:21)

Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/com.bgi.supervision.explor-1/base.apk"],nativeLibraryDirectories=[/data/app/com.bgi.supervision.explor-1/lib/arm64, /vendor/lib64, /system/lib64]]

**Comment by suo801** [comment]
解决了加上这句：
 implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.31'

什么原因呢？

**Comment by suo801** [comment]
原因是用到了kotlin的东西

**Comment by fengzhizi715** [comment]
好的 @suo801 下一个版本争取修复哈
